In [ ]:
import torch
from torch.func import jacrev, vmap

def log_density(x):
    # 簡單模擬一個高斯分佈的中心在原點：-0.5 * x^2
    return torch.sum(x**2)


single_score_fn = jacrev(log_density)
single_score_fn(torch.tensor([1.0, 2.0]))



batch_score_fn = vmap(single_score_fn)

hikers = torch.tensor([
    [1.0, 2.0],
    [2.0, 4.0],
    [0.0, 0.0],
])
print(hikers.shape)
batch_score_fn(hikers)


torch.Size([3, 2])


tensor([[2., 4.],
        [4., 8.],
        [0., 0.]])

In [25]:
x = torch.tensor([10, 20, 30, 40, 50, 60])
y = x.view(-1, 1)
print(y)

tensor([[10],
        [20],
        [30],
        [40],
        [50],
        [60]])


In [27]:
2* torch.ones(2, 2)

tensor([[2., 2.],
        [2., 2.]])

torch.Size([3, 2])


tensor([[2., 4.],
        [4., 8.],
        [0., 0.]])